//
//  RnpUISwitchChain.m
//  RnpKit
//
//  Created by Zomfice on 2019/7/31.
//

#import "RnpUISwitchChain.h"
#define RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(RPMethod,RPParaType) RPCATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(RPMethod,RPParaType, RnpUISwitchChain *,UISwitch)
@implementation RnpUISwitchChain

RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(on, BOOL);
RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(onTintColor, UIColor *);
RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(thumbTintColor, UIColor *);

RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(onImage, UIImage *);
RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION(offImage, UIImage *);

@end
RPCATEGORY_VIEW_IMPLEMENTATION(UISwitch, RnpUISwitchChain)
#undef RPCATEGORY_CHAIN_SWITCH_IMPLEMENTATION
